export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST";
export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_FAIL = "GET_ALL_JOBS_FAIL";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";

export const UPDATE_JOB_DETAILS_REQUEST = "UPDATE_JOB_DETAILS_REQUEST";
export const UPDATE_JOB_DETAILS_SUCCESS = "UPDATE_JOB_DETAILS_SUCCESS";
export const UPDATE_JOB_DETAILS_FAIL = "UPDATE_JOB_DETAILS_FAIL";
export const UPDATE_JOB_DETAILS_RESET = "UPDATE_JOB_DETAILS_RESET";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL";
export const CREATE_JOB_RESET = "CREATE_JOB_RESET";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
export const DELETE_JOB_RESET = "DELETE_JOB_RESET";

export const CREATE_JOB_APPLICATION_REQUEST = "CREATE_JOB_APPLICATION_REQUEST";
export const CREATE_JOB_APPLICATION_SUCCESS = "CREATE_JOB_APPLICATION_SUCCESS";
export const CREATE_JOB_APPLICATION_FAIL = "CREATE_JOB_APPLICATION_FAIL";
export const CREATE_JOB_APPLICATION_RESET = "CREATE_JOB_APPLICATION_RESET";

export const GET_JOB_APPLICATION_LIST_PER_JOB_REQUEST = "GET_JOB_APPLICATION_LIST_PER_JOB_REQUEST";
export const GET_JOB_APPLICATION_LIST_PER_JOB_SUCCESS = "GET_JOB_APPLICATION_LIST_PER_JOB_SUCCESS";
export const GET_JOB_APPLICATION_LIST_PER_JOB_FAIL = "GET_JOB_APPLICATION_LIST_PER_JOB_FAIL";

export const UPDATE_JOB_APPLICATION_REQUEST = "UPDATE_JOB_APPLICATION_REQUEST";
export const UPDATE_JOB_APPLICATION_SUCCESS = "UPDATE_JOB_APPLICATION_SUCCESS";
export const UPDATE_JOB_APPLICATION_FAIL = "UPDATE_JOB_APPLICATION_FAIL";
export const UPDATE_JOB_APPLICATION_RESET = "UPDATE_JOB_APPLICATION_RESET";
